version: "3.7"

services:
    oracle11gR2:
        container_name: oracle11gR2
        privileged: true
        image: manueltusset/oracle:11.2.0.2-xe
        ports:
            - 1521:1521
            - 8080:8080
        environment:
            - ORACLE_PWD=111111
            - ORACLE_SID=XE
        volumes:
            - ./data:/opt/oracle/oradata
            - ./data-bridge:/data-bridge
            - ./startup:/u01/app/oracle/scripts/startup
            - ./tablespaces:/opt/oracle/oradata/TABLESPACES
        shm_size: '2gb'
        deploy:
            resources: 
                limits: 
                    memory: '2G'