version: "3.7"

services:
    oracle11gR2:
        container_name: oracle11gR2
        privileged: true
        image: manueltusset/oracle:11.2.0.2-xe
        ports:
            - 1521:1521
            - 5500:5500
        volumes:
            - ./data:/ORCL
            - ./tablespaces:/ORCL/TABLESPACES
        deploy:
            resources: 
                limits: 
                    memory: '2G'