-- CRIA USUARIO {user}

CREATE ROLE {user} WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD '{pass}';

GRANT postgres TO {user};


-- CRIAR TABLESPACES DATA

CREATE TABLESPACE "TABLESPACES_DATA"
  OWNER {user}
  LOCATION '/var/lib/postgresql/data/pgdata/TABLESPACES_DATA';


-- CRIAR TABLESPACES INDEXES

CREATE TABLESPACE "TABLESPACES_INDEXES"
  OWNER {user}
  LOCATION '/var/lib/postgresql/data/pgdata/TABLESPACES_INDEXES';

-- CRIAR DB

CREATE DATABASE {db}
    WITH 
    OWNER = {user}
    ENCODING = 'UTF8'
    TABLESPACE = "TABLESPACES_DATA"
    CONNECTION LIMIT = -1;