# -*- mode: ruby -*-
# vi: set ft=ruby :

# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.box = 'generic/ubuntu2004'

  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = 4
    vb.memory = '6144'
    vb.name = 'ubuntu-18.04'
  end

  config.vm.provider "hyperv" do |hv|
    hv.cpus = 4
    hv.vmname = 'ubuntu-18.04'
    hv.memory = 6144
    hv.maxmemory = 6144
    hv.linked_clone = true
  end

  config.vm.network 'forwarded_port', guest: 80, host: 8080, host_ip: '127.0.0.1'
  config.vm.network 'forwarded_port', guest: 5432, host: 5432, host_ip: '127.0.0.1'
  config.vm.network 'private_network', ip: '192.168.33.10'

  config.vm.synced_folder 'vagrant-share/', '/vagrant'

  config.vm.provision 'shell', inline: <<-SHELL
    
  SHELL
end
