# -*- mode: ruby -*-
# vi: set ft=ruby :

# frozen_string_literal: true

Vagrant.configure('2') do |config|

  config.vm.box = "#{ENV['VM_Box']}"

  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = "America/Sao_Paulo"
  end

  if config.vm.box.include? "generic/rhel"
    if Vagrant.has_plugin?("vagrant-registration")
      puts "Enter your redhat registration username: "
      rhel_username = STDIN.gets.chomp
      config.registration.username = "#{rhel_username}"

      puts "Enter your redhat registration password: "
      rhel_password = STDIN.gets.chomp
      config.registration.password = "#{rhel_password}"
    end
  end

  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = 4
    vb.memory = '8192'
    vb.name = "#{ENV['VM_Name']}"
  end

  config.vm.provider "hyperv" do |hv|
    hv.cpus = 4
    hv.vmname = "#{ENV['VM_Name']}"
    hv.memory = 8192
    hv.maxmemory = 8192
    hv.linked_clone = true
  end

  config.vm.network 'forwarded_port', guest: 80, host: 8080, host_ip: '127.0.0.1'
  config.vm.network 'forwarded_port', guest: 443, host: 443, host_ip: '127.0.0.1'

  config.vm.synced_folder './scripts/', '/scripts'
  
  if "#{ENV['VM_Clean']}" === "n"
    config.vm.provision 'shell', inline: <<-SHELL
      bash /scripts/install.sh
    SHELL
  end
end
