version: "3.7"

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=l948gmSIToQjyQLpO20U
      - MSSQL_PID=Developer
    volumes:
      - ./data:/var/opt/mssql/data
    deploy:
      resources: 
        limits: 
          memory: '4G'