version: "3.7"

services:
    oracle12:
        container_name: oracle12
        image: manueltusset/oracle:12.2.0.1-ee
        privileged: true
        networks:
            - oraclenetwork
        ports:
            - 1521:1521
            - 5500:5500
        environment:
            - ORACLE_CHARACTERSET=AL32UTF8
        volumes:
            - ./data:/ORCL
        deploy:
            resources: 
                limits: 
                    memory: '2G'
networks:
    oraclenetwork:
        name: oraclenetwork