version: "3.7"

services:
    oracle12:
        container_name: oracle12
        image: store/oracle/database-enterprise:12.2.0.1
        ports:
            - 1521:1521
            - 5500:5500
        volumes:
            - ./data:/ORCL
            - ./tablespaces:/ORCL/TABLESPACES
        deploy:
            resources: 
                limits: 
                    memory: '2G'