# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.2"

Vagrant.configure("2") do |config|
    config.vm.define "vagrant-windows-2016"
    config.vm.box = "StefanScherer/windows_2016"
    config.vm.communicator = "winrm"

    # Admin user name and password
    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"

    config.vm.guest = :windows
    config.windows.halt_timeout = 15

    config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true

    config.vm.provision "shell", inline: <<-SHELL
        echo #{ENV['TAG']} >> C:\\teste.txt
        echo #{ENV['BRANCH']} >> C:\\teste.txt
    SHELL

    config.vm.provider "hyperv" do |hv|
        hv.cpus = 4
        hv.vmname = "windows_server_2016"
        hv.memory = 6144
        hv.maxmemory = 6144
        hv.linked_clone = true
    end

    config.vm.provider "virtualbox" do |vb|
        vb.cpus = 4
        vb.memory = "6144"
        vb.name = "windows_server_2016"
      end
end