version: '3.7'

services:
  sqs:
    image: localstack/localstack:latest
    container_name: sqs
    environment: 
      - AWS_DEFAULT_REGION=us-east-2
      - EDGE_PORT=4566
      - SERVICES=sqs
      - DEBUG=1
    ports:
      - 4566:4566
    volumes:
      - "./tmp_localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"