version: "3.7"

services:
    oracle19:
        container_name: oracle19
        image: manueltusset/oracle:19.3.0-xe
        ports:
            - 1521:1521
            - 5500:5500
        volumes:
            - ./data:/opt/oracle/oradata
        deploy:
            resources: 
                limits: 
                    memory: '2G'