version: "3.7"

services:
    oracle19:
        container_name: oracle19
        image: manueltusset/oracle:19.3.0-xe
        privileged: true
        ports:
            - 1521:1521
            - 5500:5500
        volumes:
            - ./data:/opt/oracle/oradata
        environment:
            - ORACLE_PWD=111111
            - ORACLE_CHARACTERSET=AL32UTF8
        deploy:
            resources: 
                limits: 
                    memory: '3G'