version: "3.7"

services:
  oracle:
    container_name: oracle
    image: manueltusset/oracle:19.3.0-ee
    privileged: true
    ports:
      - 1521:1521
      - 5500:5500
      - 8081:8081
    volumes:
      - ./data:/opt/oracle/oradata
      - ./restore:/opt/oracle/restore
      - ./scripts:/opt/oracle/scripts
      - ./containers:/opt/oracle/containers
    environment:
      - ORACLE_SID=XE
      - ORACLE_PDB=SE
      - ORACLE_PWD=111111
      - ORACLE_CHARACTERSET=AL32UTF8
    deploy:
      resources: 
        limits: 
          memory: '3G'