# -*- mode: ruby -*-
# vi: set ft=ruby :

# frozen_string_literal: true

Vagrant.configure('2') do |config|

  config.vm.box = "generic/centos8"
  config.vm.box_version = "3.4.2"

  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = 4
    vb.memory = '8192'
    vb.name = "CentOS 8"
  end

  config.vm.provider "hyperv" do |hv|
    hv.cpus = 4
    hv.vmname = "CentOS 8"
    hv.memory = 8192
    hv.maxmemory = 8192
    hv.linked_clone = true
  end

  config.vm.network 'forwarded_port', guest: 80, host: 8080, host_ip: '127.0.0.1'
  config.vm.network 'forwarded_port', guest: 443, host: 443, host_ip: '127.0.0.1'

  config.vm.synced_folder '../scripts/', '/scripts'
  
  config.vm.provision 'shell', inline: <<-SHELL
    echo "teste manuel"
  SHELL
end
