version: "3.7"

services:
    postgresql10:
        container_name: postgresql10
        image: manueltusset/postgresql:10.17
        ports:
            - 8080:8080
            - 5432:5432
        volumes:
            - .data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/var/lib/postgresql/data/pgdata
        deploy:
            resources: 
                limits: 
                    memory: '2G'