# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.2"

Vagrant.configure("2") do |config|
    config.vm.define "vagrant-windows-2019"
    config.vm.box = "StefanScherer/windows_2019"
    config.vm.communicator = "winrm"

    # Admin user name and password
    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"

    config.vm.guest = :windows
    config.windows.halt_timeout = 15

    config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true

    config.vm.provision "shell", inline: <<-SCRIPT
    echo "meu teste"
    SCRIPT

    config.vm.provider "hyperv" do |v|
        v.cpus = 2
        v.maxmemory = 2048
        v.linked_clone = true
    end
end