# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.2"

Vagrant.configure("2") do |config|

    config.vm.define "vagrant-ws2016-ltsc"
    config.vm.box = "gusztavvargadr/windows-server-standard-core"
    config.vm.box_version = "1607.0.2108"

    if Vagrant.has_plugin?("vagrant-timezone")
        config.timezone.value = "E. South America Standard Time"
    end

    # Admin user name and password
    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"

    config.vm.guest = :windows
    config.windows.halt_timeout = 15

    config.vm.network 'forwarded_port', guest: 3389, host: 3389, id: "rdp", auto_correct: true
    config.vm.network 'forwarded_port', guest: 443, host: 443, id: "https_iis", auto_correct: true
    config.vm.network 'forwarded_port', guest: 81, host: 81, id: "http_iis", auto_correct: true

    config.vm.synced_folder '../../../scripts/', 'C:\\scripts'

    config.vm.provision "shell", inline: <<-SHELL
        powershell Set-WinUserLanguageList -LanguageList pt-BR -Force
    SHELL

    config.vm.provider "hyperv" do |hv|
        hv.cpus = 4
        hv.vmname = "Windows Server 2016 Server Core"
        hv.memory = 8192
        hv.maxmemory = 8192
        hv.linked_clone = true
    end

    config.vm.provider "virtualbox" do |vb|
        vb.cpus = 4
        vb.memory = "8192"
        vb.name = "Windows Server 2016 Server Core"
        vb.gui = true
    end
end