version: "3.7"

services:
    centos7:
        container_name: centos7
        privileged: true
        image: centos:7
        deploy:
            resources: 
                limits: 
                    memory: '3G'
        command: ping localhost