version: "3.7"

services:
  postgresql:
    container_name: postgresql
    image: postgres:10.17
    ports:
      - 8080:8080
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    deploy:
      resources: 
        limits: 
          memory: '4G'