version: "3.7"

services:
  oracle:
    container_name: oracle
    image: manueltusset/oracle:21.3.0-xe
    privileged: true
    ports:
      - 1521:1521
    volumes:
      - ./data:/opt/oracle/oradata
      - ./restore:/opt/oracle/restore
      - ./backup:/opt/oracle/backup
      - ./scripts:/opt/oracle/scripts
    environment:
      - ORACLE_PDB=orcl
      - ORACLE_PWD=111111
      - ORACLE_CHARACTERSET=AL32UTF8
    deploy:
      resources: 
        limits: 
          memory: '3G'