version: "3.7"

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SqlserverDev
      - MSSQL_PID=Developer
    networks:
      - sqlnetwork
    volumes:
      - ./data:/var/opt/mssql/data
      - ./restore:/var/opt/mssql/restore
      - ./scripts:/var/opt/mssql/scripts
    deploy:
      resources: 
        limits: 
          memory: '4G'
networks:
  sqlnetwork:
    name: sqlnetwork