version: "3.7"

services:
    sqlserver19:
        container_name: sqlserver19
        image: manueltusset/sqlserver:2019
        ports:
            - 1433:1433
        networks:
            - sqlnetwork
        volumes:
            - ./data:/var/opt/mssql/data
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Sqlserver19
            - MSSQL_PID=Express
        deploy:
            resources: 
                limits: 
                    memory: '2G'
    mssql-tools:
        container_name: mssql-tools
        image: manueltusset/sqlserver:mssql-tools
        networks:
            - sqlnetwork
        deploy:
            resources: 
                limits: 
                    memory: '1G'
        command: 'ping localhost'
networks:
    sqlnetwork:
        name: sqlnetwork